config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  
  resources :users do
    resources :favourites, only: [:index]
    resources :read_states, only: [:index]
  end
  
  namespace :admin do    
    root 'users#index'
    resources :books do
      resources :reviews
    end
    resources :users
  end

  resources :books do
    resources :reviews
  end

  resources :reviews do 
    resources :comments
  end

  resources :read_states
  resources :favourites, only: [:create, :destroy]

  resources :requests, only:[:create, :new]
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  
  has_many :favourites, dependent: :destroy
  has_many :users , through: :favourites

  has_many :read_states, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :review
  belongs_to :user

  validates :content, presence: true
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/read_state.rb
class ReadState < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  scope :latest, -> (user_id, book_id) {where(user_id: user_id,
    book_id: book_id).order('created_at DESC')}
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user

  validates :content, presence: true

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :normal, ->{where role: "normal"}

  has_many :active_relationships, class_name:  "Relationship",
    foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  
  has_many :passive_relationships, class_name:  "Relationship",
    foreign_key: "followed_id", dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :reviews, dependent: :destroy

  has_many :comments, dependent: :destroy
  
  has_many :favourites, dependent: :destroy
  has_many :books, through: :favourites

  has_many :read_states, dependent: :destroy
 
  has_many :requests, dependent: :destroy
  
  def has_favourite? book
    favourites.find_by_book_id book.id
  end

  def create_favourite book
    favourites.create book_id: book.id
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end                                  
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
    @book = Book.find params[:id]
    @reviews = @book.reviews
    @new_review = @book.reviews.new
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new book_params

    respond_to do |format|
      if @book.save
        format.html { redirect_to [:admin, @book],
          notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update book_params
        format.html { redirect_to [:admin, @book],
          notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to admin_books_url,
        notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_book
      @book = Book.find params[:id]
    end

    def book_params
      params.require(:book).permit(:title, :publish_date, :author, 
        :number_page, :category, :picture)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find params[:id]
    @readstate = ReadState.latest current_user.id, @book.id
    @state = @readstate.first.state if @readstate.present?
  end

  private
    def book_params
      params.require(:book).permit(:title, :publish_date, :author, 
        :number_page, :category, :picture)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @review = Review.find params[:review_id]
    @comment = @review.comments.new comment_params
    if @comment.save
      respond_to do |format|
        format.js
      end
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit :user_id, :review_id, :content
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @user = User.find params[:user_id]
    @books = @user.books
  end

  def create
    @book = Book.find params[:book_id]
    current_user.create_favourite @book
    respond_to do |format|
      format.html {redirect_to @book}
      format.js
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id]).destroy
    @book = @favourite.book
    respond_to do |format|
      format.html {redirect_to @book}
      format.js
    end
  end
end

app/controllers/read_states_controller.rb
class ReadStatesController < ApplicationController
  
  def index
    @user = User.find params[:user_id]
    @books = @user.books
  end

  def create
    @read_state = ReadState.create state_params
    if @read_state.save
      redirect_to book_path params[:book_id]
    else 
      redirect_to book_path
    end
  end

  private

  def state_params
    params.permit :user_id, :book_id, :state    
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController  
  def new
    @request = Request.new
  end

  def create
    @request = current_user.requests.new request_params  
    if @request.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  private
  def request_params 
    params.require(:request).permit :book_name, :attr_state, :book_link
  end  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @book = Book.find params[:book_id]
    @review = @book.reviews.new review_params
    if @review.save
      respond_to do |format|
        format.js
      end
    end
  end
  
  private
  def review_params
    params.require(:review).permit :user_id, :book_id, :content
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  def index
    @users = User.all.paginate page: params[:page]
  end

  def show
    @user = User.find params[:id]
  end

  private
  def user_params
    params.require :user.permit :email, :password, :password_confirmation, :role
  end

  def logged_in_user
    unless !current_user.nil?
      redirect_to new_user_session_path
    end
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/read_states_helper.rb
module ReadStatesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/books/_controll.html.erb
<div class="box category">
  <div class="box-heading">Manage Books</div>
  <div class="box-content">
    <div class="box-category">
      <ul>
        <li><%= link_to "New Book", new_admin_book_path %></li>
        <li><%= link_to "All Book", admin_books_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publish_date %><br>
    <%= f.datetime_select :publish_date %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :number_page %><br>
    <%= f.number_field :number_page %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_books_path %>

app/views/admin/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "books">
  <h1>Listing Books</h1>

  <table>
    <tbody>
      <% @books.each do |book| %>
        <div class =  "book">

          <p>
            <%= image_tag book.picture if book.picture? %>
          </p>

          <p>
            <strong>Title:</strong>
            <%= book.title %>
          </p>

          <p>
            <strong>Publish date:</strong>
            <%= book.publish_date %>
          </p>

          <p>
            <strong>Author:</strong>
            <%= book.author %>
          </p>

          <p>
            <strong>Number page:</strong>
            <%= book.number_page %>
          </p>

          <p>
            <strong>Category:</strong>
            <%= book.category %>
          </p>

          <p>
            <%= link_to_if current_user, 'Show', admin_book_path(book) %>
            <% if current_user.role == "admin" %>
              <%= link_to 'Edit', edit_admin_book_path(book) %>
              <%= link_to 'Destroy', admin_book_path(book), method: :delete,
                data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>

        </div>
      <% end %>
    </tbody>
  </table>

<br>

<% if current_user.role == "admin" %>
  <%= link_to 'New Book', new_admin_book_path %>
<% end %>
</div>

app/views/admin/books/new.html.erb
<div class="bg_content">
<div id="column-left">
  <%= render "admin/books/controll" %>
</div>
<div id="content">
  <h1>New Book</h1>
  <%= render 'form' %>
  <%= link_to 'Back', admin_books_path %>
</div>
</div>
</div><!--   END  bg_content  -->

app/views/admin/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "books">
  <p>
    <%= image_tag @book.picture %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>

  <p>
    <strong>Publish date:</strong>
    <%= @book.publish_date %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @book.author %>
  </p>

  <p>
    <strong>Number page:</strong>
    <%= @book.number_page %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @book.category %>
  </p>

  <div class="reviews">
    <h4 id="reviews-count">This book has <%= pluralize(@book.reviews.count, 'review') %></h4>
   
    <div>
    <%= render 'reviews/review_form' %>
    </div>
  </div>
 
  <div id="reviews-list">
    <%= render partial: @book.reload.reviews %>
    <% if current_user.role == "admin" %>
      <%= link_to 'Edit', edit_admin_book_path(@book) %> |
      <%= link_to 'Back', admin_books_path %>
    <% end %>
  </div>
</div>

app/views/reviews/_review.html.erb
<%= div_for review do %>
  <div class="content">
    <div class="review-header">
      <strong>
        <p class="review-user-email"><%= sanitize(review.user.email) %>
      </strong>
          <span class="date">
            <small><%= time_ago_in_words(review.created_at) %> ago</small>
          </span>
        </p>
    </div>

    <div class="review-text">
      <p><%= sanitize(review.content) %></p>
    </div>
      
    <div class="review-footer">
      <div class="review-footer-actions">
        <button class="comment-foo-act-but" type="button" >
          Comment
        </button>
        <p>This review has <%= review.comments.count %> comment</p>
      </div>

      <div class="comment">
        
          <%= render 'comments/comment', review: review %>
        <div>
          <%= render 'comments/comment_form', review: review %>
        </div>
      </div>
    </div>
  </div>
  <p>...........................................................................................................................................................</p>
<% end %>

app/views/reviews/_review_form.html.erb
<%= form_for [@book, @book.reviews.new], remote: true do |f| %>
  <div class="form-group">
    <%= f.text_area :content, placeholder: 'Insert content review in here' %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <%= f.submit 'Post review', class: 'btn btn-primary' %>
  <div class="review-error"></div>
<% end %>

app/views/reviews/create.js.erb
<% if @review.errors.any? %>
  $('.review-error').html('<%= escape_javascript(render 'shared/error_messages', obj: @review) %>');
<% else %>
  var reviews_list = $('#reviews-list');
  reviews_list.prepend('<%= escape_javascript(render partial: @review) %>');
  $('#reviews-count').html('This book has <%= escape_javascript(pluralize(@book.reviews.count, 'review')) %>');
<% end %>