config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  
  resources :users do
    resources :favourites, only: [:index]
    resources :read_states, only: [:index]
  end
  
  namespace :admin do    
    root 'users#index'
    resources :books do
      resources :reviews
    end
    resources :users
  end

  resources :books do
    resources :reviews
  end

  resources :reviews do 
    resources :comments
  end

  resources :read_states
  resources :favourites, only: [:create, :destroy]

  resources :requests, only:[:create, :new]
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  
  has_many :favourites, dependent: :destroy
  has_many :users , through: :favourites

  has_many :read_states, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :review
  belongs_to :user

  validates :content, presence: true
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/read_state.rb
class ReadState < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  scope :latest, -> (user_id, book_id) {where(user_id: user_id,
    book_id: book_id).order('created_at DESC')}
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user

  validates :content, presence: true

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :normal, ->{where role: "normal"}

  has_many :active_relationships, class_name:  "Relationship",
    foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  
  has_many :passive_relationships, class_name:  "Relationship",
    foreign_key: "followed_id", dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :reviews, dependent: :destroy

  has_many :comments, dependent: :destroy
  
  has_many :favourites, dependent: :destroy
  has_many :books, through: :favourites

  has_many :read_states, dependent: :destroy
 
  has_many :requests, dependent: :destroy
  
  def has_favourite? book
    favourites.find_by_book_id book.id
  end

  def create_favourite book
    favourites.create book_id: book.id
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end                                  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin

  def index
    @users = User.normal.all.paginate page: params[:page]
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "User has been added!"
      redirect_to admin_users_url
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to admin_users_path
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = "User's profile has been updated!"
      redirect_to admin_users_url
    else
      render 'edit'
    end
  end

  private

  def is_admin
    unless current_user.role == "admin"
      flash[:danger] = "You not be an admin!"
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation, :role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find params[:id]
    @readstate = ReadState.latest current_user.id, @book.id
    @state = @readstate.first.state if @readstate.present?
  end

  private
    def book_params
      params.require(:book).permit(:title, :publish_date, :author, 
        :number_page, :category, :picture)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @review = Review.find params[:review_id]
    @comment = @review.comments.new comment_params
    if @comment.save
      respond_to do |format|
        format.js
      end
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit :user_id, :review_id, :content
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @user = User.find params[:user_id]
    @books = @user.books
  end

  def create
    @book = Book.find params[:book_id]
    current_user.create_favourite @book
    respond_to do |format|
      format.html {redirect_to @book}
      format.js
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id]).destroy
    @book = @favourite.book
    respond_to do |format|
      format.html {redirect_to @book}
      format.js
    end
  end
end

app/controllers/read_states_controller.rb
class ReadStatesController < ApplicationController
  
  def index
    @user = User.find params[:user_id]
    @books = @user.books
  end

  def create
    @read_state = ReadState.create state_params
    if @read_state.save
      redirect_to book_path params[:book_id]
    else 
      redirect_to book_path
    end
  end

  private

  def state_params
    params.permit :user_id, :book_id, :state    
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController  
  def new
    @request = Request.new
  end

  def create
    @request = current_user.requests.new request_params  
    if @request.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  private
  def request_params 
    params.require(:request).permit :book_name, :attr_state, :book_link
  end  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @book = Book.find params[:book_id]
    @review = @book.reviews.new review_params
    if @review.save
      respond_to do |format|
        format.js
      end
    end
  end
  
  private
  def review_params
    params.require(:review).permit :user_id, :book_id, :content
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  def index
    @users = User.all.paginate page: params[:page]
  end

  def show
    @user = User.find params[:id]
  end

  private
  def user_params
    params.require :user.permit :email, :password, :password_confirmation, :role
  end

  def logged_in_user
    unless !current_user.nil?
      redirect_to new_user_session_path
    end
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/read_states_helper.rb
module ReadStatesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/users/index.html.erb
<div class="bg_content"> 
<div id="column-left" style="background:none">
  <div id="column-right" style="margin-bottom:0px">
    <div class="box">
      <div class="box-heading"><h2>Users</h2></div>
      <div class="box-content">
        <ul class="account_list">
          <li><a href="#">List User</a></li>
          <li><a href="#">Quest'User</a></li>
          <li><a href="#">Following</a></li>
          <li><a href="#">Follower</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div id="column-right">
    <div class="box">
      <div class="box-heading"><h2>Bookshelf</h2></div>
      <div class="box-content">
        <ul class="account_list">
          <li><a href="#">Add new book</a></li>
          <li><a href="#">List Book</a></li>
          <li><a href="#">Favorite Book</a></li>
          <li><a href="#">History</a></li>
          <li><a href="#">Other Users</a></li>	             
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="content">
  <h1>List Users</h1>
  <span>  
    <div class="breadcrumb">
      <a href="#">Home</a>
      » <a href="#">AUDIOBOOKS</a>
    </div>
    
    <div id="users-list">	    
      <% @users.each do |user| %>
      <div>
        <img src="../assets/avt_default.jpg">
        <p><%= link_to user.email, admin_users_path %></p>
        <%= link_to 'Destroy', [:admin, user], confirm: 'Are you sure?', method: :delete %>
      </div>
      <% end %>
	    <%= will_paginate %>
    </div>
  </span>
<div style="clear:both"></div>
</div><!--   END  bg_content  -->

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<% @users.each do |user| %>
  <h2><%= user.email %></h2>
  </br>
<% end %>

app/views/users/show.html.erb
<div class="bg_content"> 
  <div id="column-left" style="background:none">
    <div id="column-right" style="margin-bottom:0px">
      <div class="box">
        <div class="box-heading"><h2>Users</h2></div>
        <div class="box-content">
          <ul class="account_list">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Show list favourite books", user_favourites_path(@user) %></li>
            <li><%= link_to "Show list book as read and reading", user_read_states_path(@user) %></li>
            <li><%= link_to "Send Request", new_request_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="content">
    <h1>User Profile</h1>
    <span>  
      <div class="breadcrumb">
        <a href="#">Home</a>
        » <a href="#">AUDIOBOOKS</a>
      </div>
      
      <div>      
        <h2>Email: <%= @user.email %></h2>
      </div>
    </span>
  <div style="clear:both"></div>
</div>
</div><!--   END  bg_content  -->